### ISSUE TITLE
duplicated dependencies 

### ISSUE THREAD

**Issue by HasanMhdAmin** [takahirom/dagger-hilt-multi-module-sample#1]
Hey, 
in the mentioned way, all the dependencies are duplicated, so if we need to change the version we must change it in the app class and in the all feature module.
I don't know if this is the best practices

**Comment by takahirom** [comment]
You can use buildSrc dependency with Kotlin. Please search it 😄 
https://github.com/google/iosched/tree/master/buildSrc/src/main/java
